version: '2'
services:
  es:
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.2
    build: ./build/es
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - internal
      - external
### Uncomment to enable ES persistance
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.2.2
    environment:
      ELASTICSEARCH_URL: "http://es:9200"
    networks:
      - internal
## for development
#      - external
    mem_limit: 512m
#    memswap_limit: 2g
    depends_on:
      - es
    ports:
      - "5601:5601"
  nginx:
    image: nginx
    volumes:
      - "./conf/nginx:/etc/nginx/conf.d"
      - ./certs:/etc/certs
    ports:
      - "443:443"
      - "80:80"
    #  - "127.0.0.1:8080:8080"
    networks:
      - internal
      - external
    depends_on:
      - kibana
networks:
  internal:
    internal: true
  external:
    
